### ISSUE TITLE
Cant use API because of PHP error

### ISSUE THREAD

**Issue by elzahaby** [phpList/phplist3#583]
I have tried to activate the api for my website and went for the guide on the website: 

https://www.phplist.org/manual/books/phplist-manual/page/api-and-integrations

but got an error on my way:

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'b2bliga2_phpl984.phplist_config' doesn't exist in /home/b2bliga2/public_html/newsletter/base/config/parameters.php:29 Stack trace: #0 /home/b2bliga2/public_html/newsletter/base/config/parameters.php(29): PDO->prepare('select value fr...') #1 /home/b2bliga2/public_html/newsletter/base/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php(41): include('/home/b2bliga2/...') #2 /home/b2bliga2/public_html/newsletter/base/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/PhpFileLoader.php(44): Symfony\Component\DependencyInjection\Loader\ProtectedPhpFileLoader->Symfony\Component\DependencyInjection\Loader\{closure}('/home/b2bliga2/...') #3 /home/b2bliga2/public_html/newsletter/base/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(40): Symfony\Component\DependencyInjection\Loader\PhpFileLoader->load('/home/b2bliga2/...', NULL) #4 /home/b2bliga2/pub in /home/b2bliga2/public_html/newsletter/base/config/parameters.php on line 29

checking out parameters.php on line 29 i found this:

`$statement = $pdo->prepare("select value from phplist_config where value = :value");`

which is clearly missing the table prefix, and using phplist_ as prefix??  i tried fixing that with:

`$statement = $pdo->prepare("select value from ".$table_prefix."config where value = :value");`

yet i get a server internal error when trying to acces the api:

`{"code":500,"message":"Internal Server Error"}`

**Comment by michield** [comment]
Did you install phpList? Seems like the database structure has not been created yet.

**Comment by DEllingsworth** [comment]
This issue also occurs for me.  

First error is a DBName error from 
lists/base/config/parameters.php:29
When I fix line 29 as above, I also get the 500 server error.

I would make a PR for the issue with the table name, but I don't see this file anywhere in the repo.

**Comment by michield** [comment]
Hmm, maybe this needs more attention.

**Comment by racribeiro** [comment]
I'm using a non default table prefix.

Changed line 29 on lists/base/config/parameters.php to:

$statement = $pdo->prepare("select value from " . $table_prefix . "config where value = :value");

The api call returns:
{"code":500,"message":"Internal Server Error"}

After one year, still can't find parameters.php on the github repository. The multi repository structure phplist3 and phplist4 is very confusing and doesn't map with my cPanel provided automatic instalation.

I've updated to 3.6.6 and parameters.php still has a static reference to phplist_config.

After debugging, I've found that the Mapping to the Administrator and AdministatorToken is static and, therefore, must be updated (manually?):

- base/vendor/phplist/core/src/Domain/Model/Identity/Administrator.php
- base/vendor/phplist/core/src/Domain/Model/Identity/AdministratorToken.php

After updating the references, the cache must be reset (just remove base/var/cache/prod contents and guarantee that it is writable).

Now the error reported on "prod.log" is:

request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (Object(FOS\RestBundle\View\View) given)." at /base/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 169

It seems that a render view object is returned instead of the view render result.

I don't have time to go further. Please correct this ASAP. I really would like to use the API, otherwise, I will just tap directly the database...

**Comment by michield** [comment]
Yes, work on the phpList4 based Rest API has stalled. The old one should still work though: https://resources.phplist.com/plugin/restapi

**Comment by 1F334** [comment]
Same issue, same fix, same result (500, Internal Server Error). Is there any chance to get a fix or do we have to wait for phpList 4?

**Comment by itsmemarioss** [comment]
Facing the same issue in 2026 :( 
I have installed phpList from cpanel. I have fixed the hardcoded table name but it is still failing. Not able to use it.
