### ISSUE TITLE
Rest API Problem 

### ISSUE THREAD

**Issue by beshoo** [phpList/phplist3#784]
While following the steps on 
https://www.phplist.org/manual/books/phplist-manual/page/api-and-integrations

I have this error:

```
 PHP Fatal error:  Uncaught RuntimeException: There is no composer.json in the supposed application root "/home/myranker/public_html/emaillist/lists/base". in /home/myranker/public_html/emaillist/lists/base/vendor/phplist/core/src/Core/ApplicationStructure.php:51
Stack trace:
#0 /home/myranker/public_html/emaillist/lists/base/vendor/phplist/core/src/Core/ApplicationKernel.php(70): PhpList\Core\Core\ApplicationStructure->getApplicationRoot()
#1 /home/myranker/public_html/emaillist/lists/base/vendor/phplist/core/src/Core/ApplicationKernel.php(169): PhpList\Core\Core\ApplicationKernel->getApplicationDir()
#2 /home/myranker/public_html/emaillist/lists/base/vendor/phplist/core/src/Core/ApplicationKernel.php(147): PhpList\Core\Core\ApplicationKernel->readBundleConfiguration()
#3 /home/myranker/public_html/emaillist/lists/base/vendor/phplist/core/src/Core/ApplicationKernel.php(31): PhpList\Core\Core\ApplicationKernel->bundlesFromConfiguration()
#4 /home/myranker/public_html/emaillist/lists/base/vendor/symfony/symfony/src/Symfony/Compo in /home/myranker/public_html/emaillist/lists/base/vendor/phplist/core/src/Core/ApplicationStructure.php on line 51

```
I Downloaded the PHPlist as a ZIP file and extract it on my server, and set up the config, it works just fine
But I am not sure about the composer.json installation looking for?

Please advice?

**Comment by michield** [comment]
Yes. that's discussed in #776 
Should be resolved in the next release
